<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'abstractstateclassgenerator' => '/AbstractStateClassGenerator.php',
                'classgenerator' => '/ClassGenerator.php',
                'codefilename' => '/Filename/CodeFilename.php',
                'interfacegenerator' => '/InterfaceGenerator.php',
                'specificationfilename' => '/Filename/SpecificationFilename.php',
                'specificationparser' => '/SpecificationParser.php',
                'stateclassgenerator' => '/StateClassGenerator.php',
                'templatefilename' => '/Filename/TemplateFilename.php',
                'testfilename' => '/Filename/TestFilename.php',
                'testgenerator' => '/TestGenerator.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
