<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'abstractdoorstate' => '/AbstractDoorState.php',
                'closeddoorstate' => '/ClosedDoorState.php',
                'door' => '/Door.php',
                'doorstate' => '/DoorState.php',
                'illegalstatetransitionexception' => '/IllegalStateTransitionException.php',
                'lockeddoorstate' => '/LockedDoorState.php',
                'opendoorstate' => '/OpenDoorState.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
